In [3]:
import numpy as np
import pandas as pd
from yaml import safe_load
import os
from tqdm import tqdm

In [4]:
filenames = []
for file in os.listdir('t20s'):
    file
    filenames.append(os.path.join('t20s',file))

In [5]:
filenames[0:8]

['t20s\\1001349.yaml',
 't20s\\1001351.yaml',
 't20s\\1001353.yaml',
 't20s\\1004729.yaml',
 't20s\\1007655.yaml',
 't20s\\1007657.yaml',
 't20s\\1007659.yaml',
 't20s\\1019979.yaml']

In [ ]:
#Flatting of table for ML algo

In [7]:
import pandas as pd
from tqdm import tqdm

final_df = pd.DataFrame()
counter = 1

for file in tqdm(filenames):
    with open(file, 'r') as f:
        df = pd.json_normalize(safe_load(f))
        df['match_id'] = counter
        final_df = pd.concat([final_df, df], ignore_index=True)
        counter += 1

final_df

  3%|██▋                                                                            | 163/4802 [00:34<16:19,  4.74it/s]

KeyboardInterrupt:

In [6]:
backup = final_df.copy()

NameError: name 'final_df' is not defined

In [31]:
    final_df.head()

,innings,meta.data_version,meta.created,meta.revision,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.by.wickets,info.outcome.winner,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-18,2,6,[2017-02-17],male,T20,5.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-19,2,6,[2017-02-19],male,T20,2.0,Sri Lanka,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",0.91,2017-02-23,1,6,[2017-02-22],male,T20,NaN,Australia,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",0.91,2016-09-12,1,6,[2016-09-05],male,T20,NaN,Hong Kong,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",0.91,2016-06-19,1,6,[2016-06-18],male,T20,NaN,Zimbabwe,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
final_df.drop(columns=[
    'meta.data_version',
    'meta.created',
    'meta.revision',
    'info.outcome.bowl_out',
    'info.bowl_out',
    'info.supersubs.South Africa',
    'info.supersubs.New Zealand',
    'info.outcome.eliminator',
    'info.outcome.result',
    'info.outcome.method',
    'info.neutral_venue',
    'info.match_type_number',
    'info.outcome.by.runs',
    'info.outcome.by.wickets'
],inplace=True)

In [34]:
final_df.head()

,innings,info.balls_per_over,info.dates,info.gender,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.players.Australia,info.players.Sri Lanka,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],male,T20,Sri Lanka,20,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],male,T20,Sri Lanka,20,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],male,T20,Australia,20,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],male,T20,Hong Kong,20,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],male,T20,Zimbabwe,20,[E Chigumbura],NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [41]:
final_df['info.gender'].value_counts()

info.gender
male      3046
female    1755
Name: count, dtype: int64

In [ ]:
#We only want to create regression model for male T20

In [42]:
final_df = final_df[final_df['info.gender'] == 'male']
final_df.drop(columns=['info.gender'],inplace=True)
final_df

C:\Users\ARJUN SRIVASTAVA\AppData\Local\Temp\ipykernel_27864\2142223783.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.gender'],inplace=True)

,innings,info.balls_per_over,info.dates,info.match_type,info.outcome.winner,info.overs,info.player_of_match,info.players.Australia,info.players.Sri Lanka,info.registry.people.A Zampa,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],T20,Sri Lanka,20,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],T20,Sri Lanka,20,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],T20,Australia,20,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],T20,Hong Kong,20,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],T20,Zimbabwe,20,[E Chigumbura],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-03-04],T20,Pakistan,20,[Umar Akmal],NaN,"[LD Chandimal, TM Dilshan, GSNFG Jayasuriya, C...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4797,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,[2016-03-06],T20,India,20,[S Dhawan],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4798,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,[2016-02-03],T20,Netherlands,20,[Mudassar Bukhari],NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
4799,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2016-09-06],T20,Australia,20,[GJ Maxwell],"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4800,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-09-09],T20,Australia,20,[GJ Maxwell],"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
final_df.count()

innings                                 3046
info.balls_per_over                     3046
info.dates                              3046
info.match_type                         3046
info.outcome.winner                     2940
                                        ...
info.registry.people.VS Wategaonkar        1
info.registry.people.Farhan Ahmed          2
info.registry.people.Khurram Manzoor       3
info.registry.people.P Negi                1
info.registry.people.Hafiz Qaleem          1
Length: 7741, dtype: int64

In [2]:
final_df['info.match_type'].value_counts()

NameError: name 'final_df' is not defined

In [45]:
final_df['info.overs'].value_counts()

info.overs
20    3038
50       8
Name: count, dtype: int64

In [46]:
#Only keeping 20 over matches

In [47]:
final_df = final_df[final_df['info.overs'] == 20]
final_df.drop(columns=['info.overs','info.match_type'],inplace=True)
final_df

C:\Users\ARJUN SRIVASTAVA\AppData\Local\Temp\ipykernel_27864\3157072726.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.drop(columns=['info.overs','info.match_type'],inplace=True)

,innings,info.balls_per_over,info.dates,info.outcome.winner,info.player_of_match,info.players.Australia,info.players.Sri Lanka,info.registry.people.A Zampa,info.registry.people.AJ Finch,info.registry.people.AJ Turner,...,info.registry.people.Muhammad Kaleem,info.registry.people.Usman Mushtaq,info.registry.people.Mohammad Shahid,info.registry.people.Muktar Ali,info.registry.people.Mohammad Usman,info.registry.people.VS Wategaonkar,info.registry.people.Farhan Ahmed,info.registry.people.Khurram Manzoor,info.registry.people.P Negi,info.registry.people.Hafiz Qaleem
0,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-17],Sri Lanka,[DAS Gunaratne],"[AJ Finch, M Klinger, TM Head, MC Henriques, A...","[N Dickwella, WU Tharanga, EMDY Munaweera, DAS...",14f96089,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-19],Sri Lanka,[DAS Gunaratne],"[M Klinger, AJ Finch, BR Dunk, MC Henriques, T...","[N Dickwella, WU Tharanga, EMDY Munaweera, BKG...",NaN,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2017-02-22],Australia,[A Zampa],"[AJ Finch, M Klinger, BR Dunk, TM Head, MC Hen...","[EMDY Munaweera, WU Tharanga, BKG Mendis, DAS ...",14f96089,b8d490fd,ff1e12a0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"[{'1st innings': {'team': 'Hong Kong', 'delive...",6,[2016-09-05],Hong Kong,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"[{'1st innings': {'team': 'Zimbabwe', 'deliver...",6,[2016-06-18],Zimbabwe,[E Chigumbura],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4796,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-03-04],Pakistan,[Umar Akmal],NaN,"[LD Chandimal, TM Dilshan, GSNFG Jayasuriya, C...",NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4797,"[{'1st innings': {'team': 'Bangladesh', 'deliv...",6,[2016-03-06],India,[S Dhawan],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4798,"[{'1st innings': {'team': 'Netherlands', 'deli...",6,[2016-02-03],Netherlands,[Mudassar Bukhari],NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,cee89f44,NaN,927694f7,NaN,NaN,f566cd7d
4799,"[{'1st innings': {'team': 'Australia', 'delive...",6,[2016-09-06],Australia,[GJ Maxwell],"[GJ Maxwell, DA Warner, UT Khawaja, TM Head, G...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4800,"[{'1st innings': {'team': 'Sri Lanka', 'delive...",6,[2016-09-09],Australia,[GJ Maxwell],"[DA Warner, GJ Maxwell, MC Henriques, JP Faulk...","[MDKJ Perera, TM Dilshan, DM de Silva, LD Chan...",14f96089,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
import pickle
pickle.dump(final_df,open('dataset_level1.pkl','wb'))

In [35]:
import pickle

In [ ]:
#now we are trying to create our own data better data

In [36]:
matches = pickle.load(open('dataset_level1.pkl','rb'))
matches.iloc[0]['innings'][0]['1st innings']['deliveries']

[{0.1: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.2: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.3: {'batsman': 'AJ Finch',
   'bowler': 'SL Malinga',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {0.4: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {0.5: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {0.6: {'batsman': 'M Klinger',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {1.1: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.2: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {1.3: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {1.5: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {1.6: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {2.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {2.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {2.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {2.6: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.1: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {3.2: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.3: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.4: {'batsman': 'AJ Finch',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {3.5: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {3.6: {'batsman': 'M Klinger',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.1: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.2: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {4.3: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.4: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {4.5: {'batsman': 'M Klinger',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {4.6: {'batsman': 'AJ Finch',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.1: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'wides': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {5.3: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {5.5: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {5.7: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {6.4: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {6.6: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {7.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {7.2: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {7.4: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'extras': {'byes': 1},
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {7.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {7.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.2: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {8.3: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {8.4: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.5: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {8.6: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.1: {'batsman': 'M Klinger',
   'bowler': 'S Prasanna',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {9.2: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.3: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.4: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {9.5: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {9.6: {'batsman': 'AJ Finch',
   'bowler': 'S Prasanna',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {10.1: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.2: {'batsman': 'AJ Finch',
   'bowler': 'PADLR Sandakan',
   'extras': {'legbyes': 1},
   'non_striker': 'M Klinger',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {10.3: {'batsman': 'M Klinger',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'M Klinger'}}},
 {10.4: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {10.5: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {10.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'AJ Finch',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {11.1: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {11.2: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {11.3: {'batsman': 'AJ Finch',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['SL Malinga'],
    'kind': 'caught',
    'player_out': 'AJ Finch'}}},
 {11.4: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.5: {'batsman': 'MC Henriques',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {11.6: {'batsman': 'TM Head',
   'bowler': 'DAS Gunaratne',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.1: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.2: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.3: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.4: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {12.5: {'batsman': 'TM Head',
   'bowler': 'S Prasanna',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {12.6: {'batsman': 'MC Henriques',
   'bowler': 'S Prasanna',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.1: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {13.2: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'extras': {'wides': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {13.3: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {13.5: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.6: {'batsman': 'MC Henriques',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {13.7: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.1: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.2: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.3: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {14.4: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {14.5: {'batsman': 'MC Henriques',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'TM Head',
   'runs': {'batsman': 3, 'extras': 0, 'total': 3}}},
 {14.6: {'batsman': 'TM Head',
   'bowler': 'PADLR Sandakan',
   'non_striker': 'MC Henriques',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.1: {'batsman': 'MC Henriques',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['CK Kapugedera'],
    'kind': 'caught',
    'player_out': 'MC Henriques'}}},
 {15.2: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.3: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.4: {'batsman': 'AJ Turner',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {15.5: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {15.6: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'extras': {'wides': 1},
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {15.7: {'batsman': 'TM Head',
   'bowler': 'JRMVB Sanjaya',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
 {16.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {16.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {16.3: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {16.6: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.1: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.2: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {17.3: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'noballs': 1},
   'non_striker': 'TM Head',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {17.4: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.5: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.6: {'batsman': 'AJ Turner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {17.7: {'batsman': 'TM Head',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.1: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.2: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'TM Head',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {18.3: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {18.4: {'batsman': 'TM Head',
   'bowler': 'SL Malinga',
   'non_striker': 'AJ Turner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'TM Head'}}},
 {18.5: {'batsman': 'AJ Turner',
   'bowler': 'SL Malinga',
   'non_striker': 'JP Faulkner',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0},
   'wicket': {'fielders': ['S Prasanna'],
    'kind': 'caught',
    'player_out': 'AJ Turner'}}},
 {18.6: {'batsman': 'JP Faulkner',
   'bowler': 'SL Malinga',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
 {19.1: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
 {19.2: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
 {19.3: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.4: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'extras': {'wides': 1},
   'non_striker': 'TD Paine',
   'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
 {19.5: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'TD Paine',
   'runs': {'batsman': 1, 'extras': 0, 'total': 1},
   'wicket': {'fielders': ['CK Kapugedera', 'KMDN Kulasekara'],
    'kind': 'run out',
    'player_out': 'TD Paine'}}},
 {19.6: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
 {19.7: {'batsman': 'JP Faulkner',
   'bowler': 'KMDN Kulasekara',
   'non_striker': 'PJ Cummins',
   'runs': {'batsman': 4, 'extras': 0, 'total': 4}}}]

In [37]:
matches['innings'][55]

[{'1st innings': {'team': 'Papua New Guinea',
   'deliveries': [{0.1: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'VV Morea',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.2: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'VV Morea',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {0.3: {'batsman': 'VV Morea',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.4: {'batsman': 'VV Morea',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.5: {'batsman': 'VV Morea',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Ghulam Shabber'],
       'kind': 'caught',
       'player_out': 'VV Morea'}}},
    {0.6: {'batsman': 'L Siaka',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.1: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.2: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.3: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {1.4: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {1.5: {'batsman': 'L Siaka',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.6: {'batsman': 'L Siaka',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.1: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.2: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.3: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.4: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.5: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {2.6: {'batsman': 'TP Ura',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'L Siaka',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.1: {'batsman': 'L Siaka',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.2: {'batsman': 'L Siaka',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Naveed'],
       'kind': 'caught',
       'player_out': 'L Siaka'}}},
    {3.3: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'A Vala',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.4: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {3.5: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'non_striker': 'TP Ura',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {3.6: {'batsman': 'TP Ura',
      'bowler': 'Amjad Javed',
      'non_striker': 'A Vala',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammed Qasim'],
       'kind': 'caught',
       'player_out': 'TP Ura'}}},
    {4.1: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.2: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {4.3: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {4.4: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {4.5: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {4.6: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.1: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'A Vala',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.2: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.3: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'extras': {'legbyes': 1},
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {5.4: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'A Vala',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {5.5: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'A Vala',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {5.6: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.1: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.2: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.3: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {6.4: {'batsman': 'A Vala',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {6.5: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {6.6: {'batsman': 'S Bau',
      'bowler': 'Sultan Ahmed (2)',
      'non_striker': 'A Vala',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {7.1: {'batsman': 'A Vala',
      'bowler': 'Amjad Javed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'kind': 'bowled', 'player_out': 'A Vala'}}},
    {7.2: {'batsman': 'MD Dai',
      'bowler': 'Amjad Javed',
      'extras': {'wides': 1},
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {7.3: {'batsman': 'MD Dai',
      'bowler': 'Amjad Javed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {7.4: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.5: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.6: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {7.7: {'batsman': 'S Bau',
      'bowler': 'Amjad Javed',
      'extras': {'legbyes': 2},
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 2, 'total': 2}}},
    {8.1: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.2: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.3: {'batsman': 'S Bau',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {8.4: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.5: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {8.6: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {9.1: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {9.2: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {9.3: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {9.4: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {9.5: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {9.6: {'batsman': 'S Bau',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.1: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.2: {'batsman': 'S Bau',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {10.3: {'batsman': 'S Bau',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.4: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {10.5: {'batsman': 'S Bau',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {10.6: {'batsman': 'S Bau',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.1: {'batsman': 'S Bau',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 6, 'extras': 0, 'total': 6}}},
    {11.2: {'batsman': 'S Bau',
      'bowler': 'Imran Haider',
      'extras': {'wides': 1},
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {11.3: {'batsman': 'S Bau',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.4: {'batsman': 'MD Dai',
      'bowler': 'Imran Haider',
      'non_striker': 'S Bau',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {11.5: {'batsman': 'S Bau',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {11.6: {'batsman': 'S Bau',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Muhammad Usman'],
       'kind': 'caught',
       'player_out': 'S Bau'}}},
    {11.7: {'batsman': 'JNT Vare',
      'bowler': 'Imran Haider',
      'extras': {'wides': 1},
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {11.8: {'batsman': 'JNT Vare',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.1: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {12.2: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.3: {'batsman': 'JNT Vare',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.4: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.5: {'batsman': 'JNT Vare',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {12.6: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.1: {'batsman': 'MD Dai',
      'bowler': 'Imran Haider',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {13.2: {'batsman': 'MD Dai',
      'bowler': 'Imran Haider',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.3: {'batsman': 'JNT Vare',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.4: {'batsman': 'MD Dai',
      'bowler': 'Imran Haider',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {13.5: {'batsman': 'MD Dai',
      'bowler': 'Imran Haider',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {13.6: {'batsman': 'JNT Vare',
      'bowler': 'Imran Haider',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {14.1: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {14.2: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.3: {'batsman': 'JNT Vare',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.4: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.5: {'batsman': 'JNT Vare',
      'bowler': 'Ahmed Raza',
      'non_striker': 'MD Dai',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {14.6: {'batsman': 'MD Dai',
      'bowler': 'Ahmed Raza',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {15.1: {'batsman': 'MD Dai',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'kind': 'lbw', 'player_out': 'MD Dai'}}},
    {15.2: {'batsman': 'JB Reva',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {15.3: {'batsman': 'JB Reva',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JNT Vare',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {15.4: {'batsman': 'JNT Vare',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Mohammad Naveed'],
       'kind': 'run out',
       'player_out': 'JNT Vare'}}},
    {15.5: {'batsman': 'N Vanua',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {15.6: {'batsman': 'N Vanua',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.1: {'batsman': 'N Vanua',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {16.2: {'batsman': 'N Vanua',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {16.3: {'batsman': 'N Vanua',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {16.4: {'batsman': 'N Vanua',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.5: {'batsman': 'JB Reva',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'N Vanua',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {16.6: {'batsman': 'N Vanua',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.1: {'batsman': 'N Vanua',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'JB Reva',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {17.2: {'batsman': 'JB Reva',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'N Vanua',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {17.3: {'batsman': 'JB Reva',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'N Vanua',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {17.4: {'batsman': 'JB Reva',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'N Vanua',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Amjad Javed'],
       'kind': 'caught',
       'player_out': 'JB Reva'}}},
    {17.5: {'batsman': 'N Vanua',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'A Nao',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {17.6: {'batsman': 'N Vanua',
      'bowler': 'Mohammad Naveed',
      'non_striker': 'A Nao',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'fielders': ['Ahmed Raza'],
       'kind': 'caught',
       'player_out': 'N Vanua'}}},
    {18.1: {'batsman': 'WT Gavera',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'A Nao',
      'runs': {'batsman': 2, 'extras': 0, 'total': 2}}},
    {18.2: {'batsman': 'WT Gavera',
      'bowler': 'Rohan Mustafa',
      'non_striker': 'A Nao',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0},
      'wicket': {'kind': 'bowled', 'player_out': 'WT Gavera'}}}]}},
 {'2nd innings': {'team': 'United Arab Emirates',
   'deliveries': [{0.1: {'batsman': 'Rohan Mustafa',
      'bowler': 'N Vanua',
      'extras': {'legbyes': 1},
      'non_striker': 'Mohammad Naveed',
      'runs': {'batsman': 0, 'extras': 1, 'total': 1}}},
    {0.2: {'batsman': 'Mohammad Naveed',
      'bowler': 'N Vanua',
      'non_striker': 'Rohan Mustafa',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.3: {'batsman': 'Mohammad Naveed',
      'bowler': 'N Vanua',
      'non_striker': 'Rohan Mustafa',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {0.4: {'batsman': 'Rohan Mustafa',
      'bowler': 'N Vanua',
      'non_striker': 'Mohammad Naveed',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.5: {'batsman': 'Rohan Mustafa',
      'bowler': 'N Vanua',
      'non_striker': 'Mohammad Naveed',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {0.6: {'batsman': 'Rohan Mustafa',
      'bowler': 'N Vanua',
      'non_striker': 'Mohammad Naveed',
      'runs': {'batsman': 4, 'extras': 0, 'total': 4}}},
    {1.1: {'batsman': 'Mohammad Naveed',
      'bowler': 'A Nao',
      'non_striker': 'Rohan Mustafa',
      'runs': {'batsman': 0, 'extras': 0, 'total': 0}}},
    {1.2: {'batsman': 'Mohammad Naveed',
      'bowler': 'A Nao',
      'non_striker': 'Rohan Mustafa',
      'runs': {'batsman': 1, 'extras': 0, 'total': 1}}},
    {1.3: {'batsman': 'Rohan Mustafa',
      'bowler': 'A Nao',

In [38]:
count = 1
delivery_df = pd.DataFrame()
for index, row in matches.iterrows():
    if count in [75,108,150,180,268,360,443,458,584,748,982,1052,1111,1226,1345]:
        count+=1
        continue
    count+=1
    ball_of_match = []
    batsman = []
    bowler = []
    runs = []
    player_of_dismissed = []
    teams = []
    batting_team = []
    match_id = []
    city = []
    venue = []
    for ball in row['innings'][0]['1st innings']['deliveries']:
        for key in ball.keys():
            match_id.append(count)
            batting_team.append(row['innings'][0]['1st innings']['team'])
            teams.append(row['info.teams'])
            ball_of_match.append(key)
            batsman.append(ball[key]['batsman'])
            bowler.append(ball[key]['bowler'])
            runs.append(ball[key]['runs']['total'])
            city.append(row['info.city'])
            venue.append(row['info.venue'])
            try:
                player_of_dismissed.append(ball[key]['wicket']['player_out'])
            except:
                player_of_dismissed.append('0')
    loop_df = pd.DataFrame({
            'match_id':match_id,
            'teams':teams,
            'batting_team':batting_team,
            'ball':ball_of_match,
            'batsman':batsman,
            'bowler':bowler,
            'runs':runs,
            'player_dismissed':player_of_dismissed,
            'city':city,
            'venue':venue
        })
    delivery_df = pd.concat([delivery_df, loop_df], ignore_index=True)

In [39]:
delivery_df.head()

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground

In [40]:
def bowl(row):
    for team in row['teams']:
        if team != row['batting_team']:
            return team

In [41]:
delivery_df['bowling_team'] = delivery_df.apply(bowl,axis=1)

In [42]:
delivery_df.head()

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka

In [43]:
arjun = delivery_df.copy()

In [44]:
arjun.head()

,match_id,teams,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,"[Australia, Sri Lanka]",Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,"[Australia, Sri Lanka]",Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,"[Australia, Sri Lanka]",Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,"[Australia, Sri Lanka]",Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,"[Australia, Sri Lanka]",Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka

In [47]:
delivery_df = delivery_df.drop(columns=['teams'])

KeyError: "['teams'] not found in axis"

In [46]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
365431,3039,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
365432,3039,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
365433,3039,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
365434,3039,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
365435,3039,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [48]:
delivery_df['batting_team'].value_counts()

batting_team
Pakistan                   17784
India                      16997
New Zealand                15572
Sri Lanka                  13365
South Africa               13240
                           ...
Chile                        261
Turks and Caicos Island      254
Brazil                       241
China                        218
Iran                         131
Name: count, Length: 105, dtype: int64

In [49]:
import pandas as pd
pd.reset_option('display.max_rows')

In [50]:
delivery_df['batting_team'].value_counts()

batting_team
Pakistan                   17784
India                      16997
New Zealand                15572
Sri Lanka                  13365
South Africa               13240
                           ...
Chile                        261
Turks and Caicos Island      254
Brazil                       241
China                        218
Iran                         131
Name: count, Length: 105, dtype: int64

In [51]:
counts = delivery_df['batting_team'].value_counts()
counts[counts>10000]

batting_team
Pakistan        17784
India           16997
New Zealand     15572
Sri Lanka       13365
South Africa    13240
West Indies     12935
Bangladesh      11127
England         10855
Zimbabwe        10632
Australia       10531
Name: count, dtype: int64

In [58]:
teams = [
    'Australia',
    'India',
    'Bangladesh',
    'New Zealand',
    'South Africa',
    'England',
    'West Indies',
    'Afghanistan',
    'Pakistan',
    'Sri Lanka'    
]

In [59]:
delivery_df = delivery_df[delivery_df['batting_team'].isin(teams)]
delivery_df = delivery_df[delivery_df['bowling_team'].isin(teams)]

In [60]:
delivery_df

,match_id,batting_team,ball,batsman,bowler,runs,player_dismissed,city,venue,bowling_team
0,2,Australia,0.1,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
1,2,Australia,0.2,AJ Finch,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
2,2,Australia,0.3,AJ Finch,SL Malinga,1,0,NaN,Melbourne Cricket Ground,Sri Lanka
3,2,Australia,0.4,M Klinger,SL Malinga,2,0,NaN,Melbourne Cricket Ground,Sri Lanka
4,2,Australia,0.5,M Klinger,SL Malinga,0,0,NaN,Melbourne Cricket Ground,Sri Lanka
...,...,...,...,...,...,...,...,...,...,...
365431,3039,Sri Lanka,19.3,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia
365432,3039,Sri Lanka,19.4,DM de Silva,MA Starc,0,0,Colombo,R Premadasa Stadium,Australia
365433,3039,Sri Lanka,19.5,DM de Silva,MA Starc,0,DM de Silva,Colombo,R Premadasa Stadium,Australia
365434,3039,Sri Lanka,19.6,SMSM Senanayake,MA Starc,2,0,Colombo,R Premadasa Stadium,Australia
365435,3039,Sri Lanka,19.7,SMSM Senanayake,MA Starc,1,0,Colombo,R Premadasa Stadium,Australia

In [55]:
output = delivery_df[['match_id','batting_team','bowling_team','ball','runs','player_dismissed','city','venue']]

In [65]:
output.head()

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground

In [66]:
pickle.dump(output,open('dataset_level2.pkl','wb'))

In [105]:
output[output['city'].isnull()]['venue'].value_counts()

Dubai International Cricket Stadium        2969
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: venue, dtype: int64

In [106]:
x = np.where(output['city'].isnull(), output['venue'].str.split().apply(lambda x:x[0]), output['city'])

In [107]:
output['city'] = x

<ipython-input-107-d2c7fa334a48>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  output['city'] = x

In [108]:
output.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [109]:
output.drop(columns=['venue'],inplace=True)

C:\Users\91842\anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [110]:
output

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
121,964,Sri Lanka,Australia,19.3,1,0,Colombo
122,964,Sri Lanka,Australia,19.4,0,0,Colombo
123,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
124,964,Sri Lanka,Australia,19.6,2,0,Colombo
125,964,Sri Lanka,Australia,19.7,1,0,Colombo

In [111]:
total_df = output.groupby('match_id').sum()['runs'].reset_index()
output = output.merge(total_df,on='match_id')

In [112]:
output

,match_id,batting_team,bowling_team,ball,runs_x,player_dismissed,city,runs_y
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,168
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,168
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,168
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,168
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,168
...,...,...,...,...,...,...,...,...
63883,964,Sri Lanka,Australia,19.3,1,0,Colombo,128
63884,964,Sri Lanka,Australia,19.4,0,0,Colombo,128
63885,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,128
63886,964,Sri Lanka,Australia,19.6,2,0,Colombo,128
63887,964,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [113]:
output['current_score'] = output.groupby('match_id').cumsum()['runs_x']

In [114]:
output['over'] = output['ball'].apply(lambda x:str(x).split(".")[0])
output['ball_no'] = output['ball'].apply(lambda x:str(x).split(".")[1])

In [115]:
output['balls_bowled'] = (output['over'].astype('int')*6) + output['ball_no'].astype('int')

In [116]:
output['crr'] = round((output['current_score']*6)/output['balls_bowled'],2)

In [117]:
output['player_dismissed'] = output['player_dismissed'].apply(lambda x:0 if x=='0' else 1)
output['player_dismissed'] = output['player_dismissed'].astype('int')
output['player_dismissed'] = output.groupby('match_id').cumsum()['player_dismissed']
output['wickets_left'] = 10 - output['player_dismissed']

In [128]:
final_df = output[['match_id','batting_team','bowling_team','runs_x','current_score','balls_bowled','wickets_left','crr','city','runs_y']]

In [129]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y
0,2,Australia,Sri Lanka,0,0,1,10,0.00,Melbourne,168
1,2,Australia,Sri Lanka,0,0,2,10,0.00,Melbourne,168
2,2,Australia,Sri Lanka,1,1,3,10,2.00,Melbourne,168
3,2,Australia,Sri Lanka,2,3,4,10,4.50,Melbourne,168
4,2,Australia,Sri Lanka,0,3,5,10,3.60,Melbourne,168
...,...,...,...,...,...,...,...,...,...,...
63883,964,Sri Lanka,Australia,1,125,117,2,6.41,Colombo,128
63884,964,Sri Lanka,Australia,0,125,118,2,6.36,Colombo,128
63885,964,Sri Lanka,Australia,0,125,119,1,6.30,Colombo,128
63886,964,Sri Lanka,Australia,2,127,120,1,6.35,Colombo,128
63887,964,Sri Lanka,Australia,1,128,121,1,6.35,Colombo,128

In [130]:
final_df = final_df.sample(final_df.shape[0])

In [131]:
final_df['balls_left'] = 120 - final_df['balls_bowled']
final_df['balls_left'] = final_df['balls_left'].apply(lambda x:0 if x<0 else x)

In [132]:
final_df['crr'] = round((final_df['current_score']*6)/final_df['balls_bowled'],2)

In [133]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,balls_bowled,wickets_left,crr,city,runs_y,balls_left
13793,172,India,Australia,1,68,53,9,7.70,Bengaluru,190,67
37949,612,India,South Africa,1,110,80,6,8.25,Durban,168,40
44653,690,South Africa,India,1,83,60,9,8.30,Johannesburg,219,60
25707,481,India,Australia,1,22,27,10,4.89,Durban,188,93
28922,517,Sri Lanka,West Indies,4,84,51,10,9.88,Nottingham,192,69
...,...,...,...,...,...,...,...,...,...,...,...
7179,90,India,Sri Lanka,1,51,38,9,8.05,Cuttack,180,82
8878,107,Pakistan,West Indies,1,163,98,8,9.98,Karachi,205,22
54555,817,West Indies,New Zealand,1,79,73,8,6.49,Dominica,132,47
61066,917,England,Afghanistan,0,74,79,4,5.62,Delhi,142,41
22187,447,Sri Lanka,England,1,154,111,3,8.32,Southampton,163,9

In [134]:
final_df.drop(columns=['balls_bowled'],inplace=True)

In [135]:
groups = final_df.groupby('match_id')

In [136]:
match_ids = final_df['match_id'].unique()
last_five = []
for id in match_ids:
    last_five.extend(groups.get_group(id).rolling(window=30).sum()['runs_x'].values.tolist())

In [137]:
final_df['last_five'] = last_five

In [138]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_five
13793,172,India,Australia,1,68,9,7.70,Bengaluru,190,67,NaN
37949,612,India,South Africa,1,110,6,8.25,Durban,168,40,NaN
44653,690,South Africa,India,1,83,9,8.30,Johannesburg,219,60,NaN
25707,481,India,Australia,1,22,10,4.89,Durban,188,93,NaN
28922,517,Sri Lanka,West Indies,4,84,10,9.88,Nottingham,192,69,NaN
...,...,...,...,...,...,...,...,...,...,...,...
7179,90,India,Sri Lanka,1,51,9,8.05,Cuttack,180,82,52.0
8878,107,Pakistan,West Indies,1,163,8,9.98,Karachi,205,22,53.0
54555,817,West Indies,New Zealand,1,79,8,6.49,Dominica,132,47,53.0
61066,917,England,Afghanistan,0,74,4,5.62,Delhi,142,41,NaN
22187,447,Sri Lanka,England,1,154,3,8.32,Southampton,163,9,NaN

In [139]:
final_df.dropna(inplace=True)

In [140]:
final_df

,match_id,batting_team,bowling_team,runs_x,current_score,wickets_left,crr,city,runs_y,balls_left,last_five
9124,120,South Africa,Sri Lanka,0,98,0,5.88,Colombo,98,20,40.0
63029,954,Pakistan,India,4,62,3,4.65,Mirpur,83,40,40.0
29920,528,Sri Lanka,New Zealand,0,80,8,8.00,Nottingham,158,60,41.0
20468,422,Australia,India,1,23,10,11.50,Sydney,194,108,47.0
15147,223,South Africa,Australia,1,100,8,7.69,Port Elizabeth,158,42,42.0
...,...,...,...,...,...,...,...,...,...,...,...
28042,503,Australia,New Zealand,1,52,8,7.43,Sydney,150,78,53.0
59940,908,Pakistan,Bangladesh,1,78,9,9.55,Kolkata,201,71,54.0
7179,90,India,Sri Lanka,1,51,9,8.05,Cuttack,180,82,52.0
8878,107,Pakistan,West Indies,1,163,8,9.98,Karachi,205,22,53.0
54555,817,West Indies,New Zealand,1,79,8,6.49,Dominica,132,47,53.0

In [167]:
eligible_cities = final_df['city'].value_counts()[final_df['city'].value_counts() > 600].index.tolist()
final_df = final_df[final_df['city'].isin(eligible_cities)]

In [168]:
X = final_df.drop(columns=['match_id','runs_x','runs_y'])
y = final_df['runs_y']
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [49]:
X_test

NameError: name 'X_test' is not defined

In [177]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

trf = ColumnTransformer([
    ('trf',OneHotEncoder(sparse=False,drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [212]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler()),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [213]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9510644253049361
3.1411552178006943

In [50]:
teams

['Australia',
 'India',
 'Bangladesh',
 'New Zealand',
 'South Africa',
 'England',
 'West Indies',
 'Afghanistan',
 'Pakistan',
 'Sri Lanka']